INSERT INTO TUSER (USER_CODE, USER_NAME, USER_PASSWORD, USER_DIVISION) VALUES ('00000001', 'terasoluna', 'password', '0');
INSERT INTO TUSER (USER_CODE, USER_NAME, USER_PASSWORD, USER_DIVISION) VALUES ('00000002', 'admin', 'password', '0');
INSERT INTO TUSER (USER_CODE, USER_NAME, USER_PASSWORD, USER_DIVISION) VALUES ('00000003', 'maeda', 'password', '1');
INSERT INTO TUSER (USER_CODE, USER_NAME, USER_PASSWORD, USER_DIVISION) VALUES ('00000004', 'kimura', 'password', '1');

COMMIT;
